[program:test_bot]
command=/srv/test_bot/venv/bin/python main.py
directory=/srv/test_bot
autostart=true
autorestart=true
stderr_logfile=/srv/test_bot/log/main.err.log
stdout_logfile=/srv/test_bot/log/main.out.log
user=root

[program:test_api_server]
command=/srv/test_bot/venv/bin/python api_server.py
directory=/srv/test_bot
autostart=true
autorestart=true
stderr_logfile=/srv/test_bot/log/api_server.err.log
stdout_logfile=/srv/test_bot/log/api_server.out.log
user=root
environment=API_PORT="8002"
